
title: Ivan Dianov

description: Generative art
baseurl: ""
url: "https://ivandianov.com"


plugins:
  - jekyll-feed

# Collections
permalink: /:categories/:title/
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      class: post
  - scope:
      path: ""
      type: drafts
    values:
      layout: post
      class: post

collections: 
 projects:
  output: true      

# Multiligual
lang:
  - en
  - ru

# collections: 
#  projects:
#   output: true


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
